finish build_mysql; result file: esop_mysql.tar.gz

diff --git a/esop_server_build/build_mysql/build b/esop_server_build/build_mysql/build
--- a/esop_server_build/build_mysql/build
+++ b/esop_server_build/build_mysql/build
@@ -58,19 +58,19 @@ build_mysql() {
   cp -a $PATH_EXTRACT/$dirname $PATH_OPT/mysql
   check_rc "copy $dirname as $PATH_OPT/mysql"
 
-  cp -a $PATH_TARBALL/tmp_install ${PATH_ESOP}
+  cp -rL $PATH_TARBALL/tmp_install ${PATH_ESOP}
   check_rc "copy tmp_install to ${PATH_ESOP}"
 
-  mkdir -p $PATH_ESOP/etc/mysql $PATH_ESOP/app/sbin $PATH_ESOP/data/mysql
-  check_rc "create directory etc app/sbin data/mysql"
+  mkdir -p $PATH_ESOP/etc/mysql $PATH_ESOP/app/sbin $PATH_ESOP/data/mysql $PATH_ESOP/log
+  check_rc "create directory etc/mysql app/sbin data/mysql log"
 
-  cp -a $PATH_TARBALL/etc/mysql/my.cnf $PATH_ESOP/etc/mysql
+  cp -fL $PATH_TARBALL/etc/mysql/my.cnf $PATH_ESOP/etc/mysql
   check_rc "copy etc/mysql to ${PATH_ESOP}/etc"
 
-  cp -a $PATH_TARBALL/etc/etm_init_config $PATH_ESOP/etc
+  cp -fL $PATH_TARBALL/etc/etm_init_config $PATH_ESOP/etc
   check_rc "copy etc/mysql to ${PATH_ESOP}/etc"
 
-  cp -a $PATH_TARBALL/app/sbin/eyou_toolmail $PATH_ESOP/app/sbin
+  cp -fL $PATH_TARBALL/app/sbin/eyou_toolmail $PATH_ESOP/app/sbin
   check_rc "copy etc/mysql to ${PATH_ESOP}/etc"
 
   if [ "$OS_BIT" == "64" ]; then
@@ -91,7 +91,7 @@ make_tarball() {
   mkdir -p $tar_createdir/files
   check_rc "create local $tar_createdir/files"
   
-  cp -a "${PATH_ESOP}"  $tar_createdir/files
+  cp -a ${PATH_ESOP}/*  $tar_createdir/files
   check_rc "copy $PATH_ESOP to local $tar_createdir/files"
 
   cp -a $PATH_TARBALL/install $tar_createdir
@@ -100,7 +100,7 @@ make_tarball() {
   cd $BASE_DIR
   check_rc "changing into $BASE_DIR"
 
-  tar -czf $tar_filename $tar_createdir
+  tar -czf $tar_filename ${tar_createdir##*/}
   check_rc "make tarball on $tar_createdir for $BASE_DIR/$tar_filename"
 
   rm -rf $tar_createdir
@@ -108,6 +108,11 @@ make_tarball() {
 }
 
 ### Main Body Begin ...
+
+if [ "$(id -u)" != "0" ]; then
+  echo " root privileges required! "
+  exit 1
+fi
 
 echo -e "\n -- $(date +%F_%T) -- BUILD START -- \n\n" >> $LOGFILE
 
diff --git a/esop_server_build/build_mysql/opt/balls/install b/esop_server_build/build_mysql/opt/balls/install
--- a/esop_server_build/build_mysql/opt/balls/install
+++ b/esop_server_build/build_mysql/opt/balls/install
@@ -6,29 +6,31 @@ export PATH="${PATH}:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/l
 ### GLOBAL DEF
 BASE_DIR="$(cd $(dirname $0); pwd)"
 LOGFILE="${BASE_DIR}/${0##*/}.log"
+FILEDIR="${BASE_DIR}/files"
 
 # DIR DEF
 PATH_ESOP="/usr/local/eyou/toolmail"
 PATH_OPT="${PATH_ESOP}/opt"
+PATH_LOG="${PATH_ESOP}/log"
 PATH_MYSQL="${PATH_OPT}/mysql"
 PATH_APP="${PATH_ESOP}/app"
 PATH_SBIN="${PATH_APP}/sbin"
 PATH_ETC="${PATH_ESOP}/etc"
+PATH_TMPINST="${PATH_ESOP}/tmp_install"
+PATH_TMPSQL="${PATH_TMPINST}/sql/"
 
 # FILE DEF
 INIT_SH="${PATH_SBIN}/eyou_toolmail"
 MYSQL_CLI="${PATH_MYSQL}/bin/mysql"
-MYSQL_CONF="${PATH_ECT}/mysql/my.cnf"
+MYSQL_CONF="${PATH_ETC}/mysql/my.cnf"
 MYSQL_DATA="${PATH_ESOP}/data/mysql/"
 
 USER="eyou"
-UID="12037"
+USERID="12037"
 
 # SUDO DEF
 SUDO="sudo -u ${USER}"
 
-# DATABASE DEF
-DATABASE="eyou_monitor"
 
 # Global Func Def
 
@@ -42,24 +44,13 @@ check_rc() {
   fi
 }
 
-
-### Main Body Begin
-
-if [ -f ${MYSQL_CLI} -a -x ${MYSQL_CLI} ]; then
-	MYSQL_CLI="${MYSQL_CLI} -h 127.1 -P 3308"
-else
-	echo "${MYSQL_CLI} not prepared!"
-	exit 1
-fi
-
-
 # create system user
 add_user() {
 	if id ${USER} >/dev/null 2>&1; then
-		:
+		check_rc "no need to add system user ($USER)"
 	else
-        	useradd ${USER} -m -d /usr/local/%{name}/ -u ${UID} >/dev/null 2>&1
-		check_rc "add system user $USER($UID)"
+        	useradd ${USER} -m -d /usr/local/%{name}/ -u ${USERID} >/dev/null 2>&1
+		check_rc "add system user $USER($USERID)"
 	fi
 }
 
@@ -68,18 +59,17 @@ init_db() {
 	cd "${PATH_MYSQL}" >/dev/null 2>&1
 	check_rc "chaning directory into ${PATH_MYSQL}"
 
-	/bin/chown -R eyou:eyou ${MYSQL_DATA}
-	check_rc "change ower/group as eyou:eyou for ${MYSQL_DATA}"
+	/bin/chown -R eyou:eyou ${MYSQL_DATA} ${PATH_LOG}
+	check_rc "change ower/group as eyou:eyou for ${MYSQL_DATA}" 
 
-	${SUDO} ./scripts/mysql_install_db --defaults-file=${MYSQL_CONF} --datadir=${MYSQL_DATA}
+	${SUDO} ./scripts/mysql_install_db --defaults-file=${MYSQL_CONF} --datadir=${MYSQL_DATA} >> $LOGFILE 2>&1
 	check_rc "init install mysql db to ${MYSQL_DATA}"
 }
 
 # start mysql db
 start_mysql() {
-	${INIT_SH} start mysql
-	wait
-	# check mysql start succeed here!
+	${INIT_SH} start mysql >> $LOGFILE 2>&1
+	check_rc "start mysql"
 }
 
 # remove useless database/user
@@ -93,10 +83,10 @@ clean_mysql() {
 
 # create database/tables, grant privileges
 init_eyoumonitor() {
-	${MYSQL_CLI} -s -e -D ${DATABASE} < sql/db_creation_eyou_monitor.sql
+	${MYSQL_CLI} -s < $PATH_TMPSQL/db_creation_eyou_monitor.sql
 	check_rc "create eyou_monitor schema"
 
-	${MYSQL_CLI} -s -e -D ${DATABASE} < sql/db_init_eyou_monitor.sql
+	${MYSQL_CLI} -s < $PATH_TMPSQL/db_init_eyou_monitor.sql
 	check_rc "initialize eyou_monitor data"
 
 	${MYSQL_CLI} -s -e "GRANT ALL PRIVILEGES ON eyou_monitor.* TO eyou@127.0.0.1 IDENTIFIED BY 'eyou' WITH GRANT OPTION;" 
@@ -105,3 +95,37 @@ init_eyoumonitor() {
 	${MYSQL_CLI} -s -e "GRANT ALL PRIVILEGES ON eyou_monitor.* TO eyou@localhost IDENTIFIED BY 'eyou' WITH GRANT OPTION;"
 	check_rc "grant eyou@localhost"
 }
+
+
+### Main Body Begin
+
+if [ "$(id -u)" != "0" ]; then
+  echo " root privileges required! "
+  exit 1
+fi 
+
+if [ -d ${PATH_ESOP} ]; then
+  echo " ${PATH_ESOP} already exist! rename or remove it! " | tee -a $LOGFILE
+  exit 1
+else
+  /bin/mkdir -p ${PATH_ESOP}
+  check_rc "create directory ${PATH_ESOP}"
+
+  /bin/cp -a $FILEDIR/* ${PATH_ESOP}
+  check_rc "copy files to ${PATH_ESOP}"
+fi
+
+
+if [ -f ${MYSQL_CLI} -a -x ${MYSQL_CLI} ]; then
+	MYSQL_CLI="${MYSQL_CLI} -h 127.1 -P 3308"
+else
+	echo "${MYSQL_CLI} not prepared!"
+	exit 1
+fi
+
+
+add_user
+init_db
+start_mysql
+clean_mysql
+init_eyoumonitor
