bugfix on mole daemon: turn off STDOUT,STDERR; changing into /

diff --git a/sbin/mole b/sbin/mole
--- a/sbin/mole
+++ b/sbin/mole
@@ -358,7 +358,26 @@ else
 	
 	gettext "7. starting mole cron        ... "
 	write_log -f "${MOLE_LOG}" "S0000000 MOLE starting mole core cron... "
-	{ while : ; do
+
+	cd / >/dev/null 2>&1;
+	if [ "$?" != "0" -o "$(pwd -P)" != "/" ]; then
+		echo -e "[$(echo_red "$(gettext "changing into / failed!")")]"
+		echo "123"
+		exit 1;
+	fi
+
+	umask 0000 >/dev/null 2>&1;
+	if [ "$?" != "0" -o "$(umask)" != "0000" ]; then
+		echo -e "[$(echo_red "$(gettext "chaning umask failed!")")]"
+		exit 1;
+	fi
+
+	{ 
+
+	exec 1>&-
+	exec 2>&-
+
+	while : ; do
 		
 		### trap signal HUP to reload bin/include
 		trap '  write_log -f "${MOLE_LOG}" "TRAP0000 MOLE Main:::Caught:::SIGHUP, Reloading..."
