start build for build_api

diff --git a/esop_server_build/build_api/build b/esop_server_build/build_api/build
--- a/esop_server_build/build_api/build
+++ b/esop_server_build/build_api/build
@@ -8,17 +8,10 @@ LOG_DIR="${BASE_DIR}/logs"
 LOGFILE="${BASE_DIR}/logs/${0##*/}.log"
 
 PATH_TARBALL="${BASE_DIR}/opt/balls"
-PATH_EXTRACT="${BASE_DIR}/opt/extract"
 
 PATH_ESOP="/usr/local/eyou/toolmail"
 
-mkdir -p "${PATH_TARBALL}" "${PATH_EXTRACT}" "${LOG_DIR}"
 
-
-[ "$1" == "clean" ] && {
-   rm -rf "${PATH_EXTRACT}"
-   exit 0
-}
 
 # Command Def
 
@@ -41,35 +34,90 @@ check_rc() {
   fi
 }
 
-# -- build_esopserver_code
-build_esopserver_code() {
-  local filename="esopserver-1.0-beta1.tgz"  dirname="esopserver-1.0-beta1"
+# -- build_apicode
+build_apicode() {
 
-  $CMD_UNTAR_GZ $PATH_TARBALL/$filename -C $PATH_EXTRACT
+  mkdir -p $PATH_ESOP/etc $PATH_ESOP/app $PATH_ESOP/log $PATH_ESOP/run
+  check_rc "create directory etc app log run"
 
-  cp -a $PATH_EXTRACT/$dirname/*  $PATH_ESOP/
-  check_rc "install $dirname to $PATH_ESOP"
+  cp -a $PATH_TARBALL/implements $PATH_ESOP
+  check_rc "copy implements to $PATH_ESOP"
+
+  cp -a $PATH_TARBALL/app/bin/  $PATH_ESOP/app
+  check_rc "copy app/bin to $PATH_ESOP"
+
+  cp -a $PATH_TARBALL/app/inc/  $PATH_ESOP/app
+  check_rc "copy app/inc to $PATH_ESOP"
+
+  cp -a $PATH_TARBALL/app/lib/  $PATH_ESOP/app
+  check_rc "copy app/lib to $PATH_ESOP"
+
+  cp -a $PATH_TARBALL/app/sbin/  $PATH_ESOP/app
+  check_rc "copy app/sbin to $PATH_ESOP"
+
+  cp -fL $PATH_TARBALL/etc/etm_allow_ip.ini $PATH_ESOP/etc
+  check_rc "copy etc/etm_allow_ip.ini to $PATH_ESOP"
+
+  cp -fL $PATH_TARBALL/etc/etm_init_config $PATH_ESOP/etc
+  check_rc "copy etc/etm_init_config to $PATH_ESOP"
+
+  cp -fL $PATH_TARBALL/etc/etm_phptd.ini $PATH_ESOP/etc
+  check_rc "copy etc/etm_phptd.ini to $PATH_ESOP"
+
+  cp -fL $PATH_TARBALL/etc/eyou_toolmail.ini $PATH_ESOP/etc
+  check_rc "copy etc/eyou_toolmail.ini to $PATH_ESOP"
 }
 
-install_sh() {
-  local sh1="sbin/init_install" sql1="sql/db_creation_eyou_monitor.sql" sql2="sql/db_init_eyou_monitor.sql"
+# -- make_tarball 
+make_tarball() {
 
-  mkdir -p $PATH_ESOP/tmp_install/sbin/
-  check_rc "create $PATH_ESOP/tmp_install/sbin/"
+  local tar_createdir="$BASE_DIR/esop_api"
+  local tar_filename="esop_api.tar.gz"
 
-  cp $PATH_TARBALL/"$sh1" "$PATH_ESOP/tmp_install/sbin/"
-  check_rc "install $sh1 to $PATH_ESOP/tmp_install/sbin/"
+  mkdir -p $tar_createdir/files
+  check_rc "create local $tar_createdir/files"
 
-  mkdir -p $PATH_ESOP/tmp_install/sql/
-  check_rc "create $PATH_ESOP/tmp_install/sql/"
+  cp -a ${PATH_ESOP}/*  $tar_createdir/files
+  check_rc "copy $PATH_ESOP to local $tar_createdir/files"
 
-  cp $PATH_TARBALL/"$sql1" $PATH_TARBALL/"${sql2}" "$PATH_ESOP/tmp_install/sql/"
-  check_rc "install $sql1 $sql2 to $PATH_ESOP/tmp_install/sql/"
+  cp -a $PATH_TARBALL/install $tar_createdir
+  check_rc "copy $PATH_TARBALL/install  to local $tar_createdir/"
+
+  cd $BASE_DIR
+  check_rc "changing into $BASE_DIR"
+
+  tar -czf $tar_filename ${tar_createdir##*/}
+  check_rc "make tarball on $tar_createdir for $BASE_DIR/$tar_filename"
+
+  rm -rf $tar_createdir
+  check_rc "remove $tar_createdir"
 }
+
+
 
 ### Main Body Begin ...
 
+if [ "$(id -u)" != "0" ]; then
+  echo " root privileges required! "
+  exit 1
+fi
+
 echo -e "\n -- $(date +%F_%T) -- BUILD START -- \n\n" >> $LOGFILE
-build_esopserver_code
-install_sh
+
+
+if [ -d "${PATH_ESOP}" ]; then
+  rm -rf "${PATH_ESOP}"
+  check_rc "remove ${PATH_ESOP}"
+fi
+
+if [ -d "${PATH_EXTRACT}" ]; then
+  rm -rf "${PATH_EXTRACT}"
+  check_rc "remove ${PATH_EXTRACT}"
+fi
+
+
+build_apicode
+make_tarball
+
+
 echo -e "\n -- $(date +%F_%T) -- BUILD END -- \n\n" >> $LOGFILE
